image: registry.gitlab.com/4tu/spheal

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  stage: deploy
  script:
    - pacman -Syu || true
    - pacman --noconfirm -S doxygen
    - doxygen
    - mkdir -p public
    - cp -r docs/html/* public
  artifacts:
    paths:
      - public

.common: &common
  script:
    - git clone https://gitlab.com/4TU/chestotesto.git /chestotesto
    - cp -rf . /chestotesto/libs/chesto
    - (cd /chestotesto && make $PLATFORM)
    - cp /chestotesto/chestotesto.$EXT chestotesto.$EXT
  artifacts:
    paths:
      - chestotesto.$EXT

PC:
  <<: *common
  variables:
    PLATFORM: pc
    EXT: bin

PC-sdl1:
  <<: *common
  variables:
    PLATFORM: pc-sdl1
    EXT: bin-sdl1

WiiU:
  <<: *common
  variables:
    PLATFORM: wiiu
    EXT: rpx

Switch:
  <<: *common
  variables:
    PLATFORM: switch
    EXT: nro

3ds:
  <<: *common
  variables:
    PLATFORM: 3ds
    EXT: 3dsx

Wii:
  <<: *common
  variables:
    PLATFORM: wii
    EXT: dol
